// frontend/src/components/JobList.tsx
import React, { useState, useEffect } from 'react';
import JobListing from './JobListing';

interface Job {
  id: number;
  title: string;
  company: string;
  location: string;
  description: string;
  technologies: string[];
  posted_season: string;
}

const JobList: React.FC = () => {
  const [jobs, setJobs] = useState<Job[]>([]);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchJobs = async () => {
      try {
        const response = await fetch('http://localhost:8000/api/jobs');
        if (!response.ok) {
          throw new Error('Network response was not ok');
        }
        const data: Job[] = await response.json();
        setJobs(data);
      } catch (error) {
        setError('Failed to fetch jobs. Is the backend server running?');
        console.error('There was a problem with the fetch operation:', error);
      }
    };

    fetchJobs();
  }, []);

  if (error) {
    return <div class="error">{error}</div>;
  }

  return (
    <div class="job-list">
      <h1>Job Listings</h1>
      {jobs.length > 0 ? (
        jobs.map(job => <JobListing key={job.id} job={job} />)
      ) : (
        <p>Loading jobs...</p>
      )}
    </div>
  );
};

export default JobList;

// src/components/JobList.vue
<template>
  <div class="job-list">
    <ul>
      <li v-for="job in jobs" :key="job.id">
        <h2>{{ job.title }}</h2>
        <h3>{{ job.company }}</h3>
        <p>{{ job.location }}</p>
        <p>{{ job.description }}</p>
        <div>
          <strong>Technologies:</strong>
          <ul>
            <li v-for="tech in job.technologies" :key="tech">{{ tech }}</li>
          </ul>
        </div>
      </li>
    </ul>
  </div>
</template>

<script lang="ts">
import { defineComponent, PropType } from 'vue';

interface Job {
  id: number;
  title: string;
  company: string;
  location: string;
  description: string;
  technologies: string[];
}

export default defineComponent({
  name: 'JobList',
  props: {
    location: {
      type: String as PropType<string>,
      default: ''
    },
    technologies: {
      type: String as PropType<string>,
      default: ''
    }
  },
  data() {
    return {
      jobs: [] as Job[]
    };
  },
  methods: {
    async fetchJobs() {
      try {
        let url = 'http://localhost:8000/api/jobs';
        const params = new URLSearchParams();
        if (this.location) {
          params.append('location', this.location);
        }
        if (this.technologies) {
          params.append('technologies', this.technologies);
        }
        if (params.toString()) {
          url += `?${params.toString()}`;
        }
        const response = await fetch(url);
        if (!response.ok) {
          throw new Error('Failed to fetch jobs');
        }
        this.jobs = await response.json();
      } catch (error) {
        console.error(error);
      }
    }
  },
  watch: {
    location() {
      this.fetchJobs();
    },
    technologies() {
      this.fetchJobs();
    }
  },
  mounted() {
    this.fetchJobs();
  }
});
</script>

<style scoped>
.job-list {
  max-width: 800px;
  margin: 0 auto;
}
ul {
  list-style-type: none;
  padding: 0;
}
li {
  border: 1px solid #ccc;
  padding: 1rem;
  margin-bottom: 1rem;
}
</style>
