// src/App.tsx
import React, { useState } from 'react';

const App: React.FC = () => {
  const [name, setName] = useState('Link');
  const [age, setAge] = useState<string | number>(17);

  const changeName = (newName: string) => {
    setName(newName);
  };

  const changeAge = (newAge: number) => {
    setAge(newAge);
  };

  return (
    <div className="app">
      <p>{name} - {age}</p>
      <button onClick={() => changeName('Zelda')}>Change Name</button>
      <button onClick={() => changeAge(18)}>Change Age</button>
    </div>
  );
};

export default App;

// src/App.vue
<template>
  <div class="app">
    <p>{{ name }} - {{ age }}</p>
    <button @click="ChangeName('Zelda')">Change Name</button>
    <button @click="ChangeAge(18)">Change Age</button>
  </div>
</template>

<script lang="ts">
  import { defineComponent, reactive, ref, toRef } from 'vue';

  export default defineComponent({
    name: 'App',
    components: {},
    setup() {
      const name = ref('Link');
      const age = ref<string | number>(17);

      return {
        name,
        age
      }
    },
    methods: {
      ChangeName(name: string){
        this.name = name;
      },
      ChangeAge(age: number | string){
        this.age = age;
      }
    }
  });
</script>

<style>
</style>
